# TODO: Adapt https://github.com/sindresorhus/pure for starship config

# Timeout for commands executed by starship (in milliseconds).
command_timeout	= 1000

[character]
success_symbol = "[âœ](bold green)"
error_symbol = "[âœ](bold red)"

[nodejs]
symbol = "ğŸ¢ ğŸš€ "
